apiVersion: monitoring.coreos.com/v1alpha1
kind: AlertmanagerConfig
metadata:
  creationTimestamp: null
  labels:
    app: testing-app
    release: kube-prometheus-stack
  name: testing-app
  namespace: scoutflo-monitoring
spec:
  receivers:
  - name: slack-integration
    slackConfigs:
    - apiURL:
        key: webhook_url
        name: custom-slack-webhook
      channel: prometheus-alertmanager-freetrial
      sendResolved: true
      text: |-
        {{ range .Alerts }}{{ .Annotations.description }}
        {{ end }}
      title: |-
        {{ range .Alerts }}{{ .Annotations.summary }}
        {{ end }}
  route:
    groupBy:
    - alertname
    - cluster
    - service
    - namespace
    groupInterval: 10s
    groupWait: 10s
    matchers:
    - name: app
      value: manav-app-1
    receiver: slack-integration
    repeatInterval: 10s
