apiVersion: monitoring.coreos.com/v1
kind: PrometheusRule
metadata:
  annotations:
    prometheus-operator-validated: "true"
  creationTimestamp: "2024-11-12T21:48:04Z"
  generation: 4
  managedFields:
  - apiVersion: monitoring.coreos.com/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:spec:
        .: {}
        f:groups:
          .: {}
          k:{"name":"testing-1app"}:
            .: {}
            f:interval: {}
            f:name: {}
            f:rules: {}
    manager: main
    operation: Update
    time: "2024-11-12T22:17:44Z"
  name: testing-1app
  namespace: manav-monitoring
  resourceVersion: "48781060"
  uid: 83a99f33-b42c-4af2-acdf-b8f6c6e8126f
spec:
  groups:
  - interval: 30s
    name: testing-1app
    rules:
    - alert: example
      expr: job:request_latency_seconds:mean5m{job='myjob'} > 0.5
      labels:
        severity: warning
    - alert: example
      expr: job:request_latency_seconds:mean5m{job='myjob'} > 0.5
      labels:
        severity: warning
    - alert: example
      expr: job:request_latency_seconds:mean5m{job='myjob'} > 0.5
      labels:
        severity: warning
    - alert: example
      expr: job:request_latency_seconds:mean5m{job='myjob'} > 0.5
      labels:
        severity: warning
    - alert: example
      expr: job:request_latency_seconds:mean5m{job='myjob'} > 0.5
      labels:
        severity: warning
